name: eco_step
description: "e-icon project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get: ^4.7.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_serializable: ^6.10.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/.env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
    - family: ClimateCrisis
      fonts:
        - asset: assets/fonts/ClimateCrisis-Regular-VariableFont_YEAR.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
